language: python
python:
  - 3.6
  - 3.7
  - 3.8

env:
  - REQUESTS_VERSION="latest" PYTZ_VERSION="latest"
  - REQUESTS_VERSION="latest" PYTZ_VERSION="oldest"
  - REQUESTS_VERSION="oldest" PYTZ_VERSION="latest"
  - REQUESTS_VERSION="oldest" PYTZ_VERSION="oldest"

install:
  - python setup.py install
  - pip install tox-travis

script: tox
